/* Generated by Together */

package nl.tue.declare.domain.organization;

import nl.tue.declare.domain.*;

class Person
    extends Base {

  private String name = "";
  private String lastName = "";
  /**
   * Person
   *
   * @param aId int
   */
  public Person(int aId) {
    super(aId);
  }

  public void setName(String name) {
    this.name = name;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public String getName() {
    return name;
  }

  public String getLastName() {
    return lastName;
  }

  /**
   * getFullName
   *
   * @return String
   */
  public String getFullName() {
    return getName() + " " + getLastName();
  }

  /**
   * toString
   *
   * @return String
   */
  public String toString() {
    return getFullName();
  }

}
